{
 "title": "Room Air Quality",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "CO2",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    { "expr": "aranet4_co2_ppm", "legendFormat": " " }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "aranet4_temperature_c", "legendFormat": " " }
   ]
  },
  {
   "title": "Battery",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aranet4_battery_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Agent Up",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"localhost:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "aranet4_humidity_percent", "legendFormat": " " }
   ]
  },
  {
   "title": "Atmospheric Pressure",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    { "expr": "aranet4_pressure_hpa + 24", "legendFormat": " " }
   ]
  }
 ]
}