---

- name: Setup Aranet4 sensor
  hosts: "{{ variable_host | default('rpi') }}"
  become: true
  vars:
    device: "{{ aranet_device }}"  # in format "DD:...:1F=office"
    interval: "{{ aranet_interval | default(60) }}"
  pre_tasks:
    - name: Test connection with ping
      ansible.builtin.ping:
  tasks:
    - name: Install Aranet .deb package
      ansible.builtin.apt:
        deb: https://github.com/MartinHeinz/aranet4-exporter-go/releases/download/v1.0.1/aranet4-exporter_1.0.1_linux_armv6.deb

    - name: Configure service
      ansible.builtin.template:
        src: templates/aranet4-exporter.j2
        dest: /etc/default/aranet4-exporter
        owner: root
        group: root
        mode: '0644'

    - name: Restart Aranet service
      ansible.builtin.systemd:
        state: restarted
        name: aranet4-exporter