---

- name: Setup RPi
  hosts: "{{ variable_host | default('rpi') }}"
  become: true
  vars:
    docker_install_compose: true
    docker_compose_arch: armv7
    pip_install_packages:
      - name: docker
  roles:
    - geerlingguy.pip
    - geerlingguy.docker

  tasks:
    - name: Install Bluetooth packages
      ansible.builtin.apt:
        pkg:
          - bluetooth
          - pi-bluetooth
          - bluez